collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5537634
  brandStrength: 0
  lightness: 0.5358423
  brandColors:
    - '#050B05'
    - '#545B65'
    - '#CFAA7F'
    - '#FFE09A'
    - '#FFFFFF'
  rhythmicContrast: 0.5412186
typography_spectrum: 0.5519713
layout_spectrum: 0.6218638
name: IOSHOOT
