collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3835126
  brandStrength: 0.5376344
  lightness: 0.3351254
  brandColors:
    - '#EAD1B2'
    - '#3A2E30'
    - '#87645E'
    - '#9B999A'
  rhythmicContrast: 0.3351254
typography_spectrum: 0.5519713
layout_spectrum: 0.530466
name: IOSHOOT
