collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.04480287
  lightness: 0.7293907
  brandColors:
    - '#050B05'
    - '#545B65'
    - '#CFAA7F'
    - '#FFE09A'
    - '#FFFFFF'
  rhythmicContrast: 0.8046595
typography_spectrum: 0.5519713
layout_spectrum: 1
name: IOSHOOT
