layout_spectrum: 0.8172043
color:
  saturation: 0.4677419
  brandStrength: 0.6810036
  lightness: 0.5412186
  brandColors:
    - '#040402'
    - '#4A4C4C'
    - '#FFA466'
    - '#FFFFFC'
    - '#54F1D0'
  rhythmicContrast: 0.3691756
typography_spectrum: 0.5519713
name: IOSHOOT
